# Generated by Django 2.2.1 on 2019-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20190522_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfeedback',
            name='to',
            field=models.BooleanField(default=False),
        ),
    ]
