# Generated by Django 2.2.1 on 2019-06-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_sendfeedback_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendfeedback',
            name='to',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
