# Generated by Django 2.2.1 on 2019-06-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auto_20190612_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendfeedback',
            name='to',
        ),
        migrations.AddField(
            model_name='sendfeedback',
            name='to_dep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticate.Department'),
        ),
        migrations.AddField(
            model_name='sendfeedback',
            name='to_fac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticate.Faculty'),
        ),
    ]
