# Generated by Django 2.2.1 on 2019-06-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_auto_20190612_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendfeedback',
            name='to_dep',
        ),
        migrations.RemoveField(
            model_name='sendfeedback',
            name='to_fac',
        ),
    ]
