# Generated by Django 2.2.1 on 2019-06-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_auto_20190612_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfeedback',
            name='to_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticate.Department'),
        ),
        migrations.AddField(
            model_name='sendfeedback',
            name='to_faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authenticate.Faculty'),
        ),
    ]
