# Generated by Django 2.2.1 on 2019-06-12 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_auto_20190612_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfeedback',
            name='deparment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendfeedback',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sendfeedback',
            name='to_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sendfeedback',
            name='to_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
