# Generated by Django 2.2.1 on 2019-06-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_auto_20190612_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendfeedback',
            old_name='deparment',
            new_name='department',
        ),
    ]
