# Generated by Django 2.2.1 on 2019-06-12 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_auto_20190612_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendfeedback',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_department', to='authenticate.Department'),
        ),
        migrations.AlterField(
            model_name='sendfeedback',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_faculty', to='authenticate.Faculty'),
        ),
    ]
