# Generated by Django 2.2.1 on 2019-06-12 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_auto_20190612_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendfeedback',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sendfeedback',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_faculty', to=settings.AUTH_USER_MODEL),
        ),
    ]
