# Generated by Django 2.2.1 on 2019-06-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_auto_20190612_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendfeedback',
            name='facu',
        ),
        migrations.AddField(
            model_name='sendfeedback',
            name='facult',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_faculty', to='authenticate.Faculty'),
        ),
        migrations.AlterField(
            model_name='sendfeedback',
            name='depart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_department', to='authenticate.Department'),
        ),
    ]
