# Generated by Django 2.2.2 on 2019-06-19 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0014_auto_20190613_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='read_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
